<?xml version="1.0" encoding="UTF-8"?>
    <!--
        Palette Metadata

        This document provides additional designtime metadata for various Android views, such as
        logical palette categories (as well as a natural ordering of the views within their
        categories, fill-preferences (how a view will sets its width and height attributes when
        dropped into other views), and so on.
    -->
<!DOCTYPE metadata [
<!--- The metadata consists of a series of category definitions -->
<!ELEMENT metadata (category)*>
<!--- Each category has a name and contains a list of views in order -->
<!ELEMENT category (view)*>
<!ATTLIST category name CDATA #IMPLIED>
<!--- Each view is identified by its full class name and has various
      other attributes such as a fill preference  -->
<!ELEMENT view (view)*>
<!ATTLIST view
    class CDATA #IMPLIED
    name CDATA #IMPLIED
    init CDATA #IMPLIED
    icon CDATA #IMPLIED
    relatedTo CDATA #IMPLIED
    skip (true|false) "false"
    render (alone|skip|normal) "normal"
    fill ( none|both|width|height|opposite|
          width_in_vertical|height_in_horizontal) "none"
>
]>
<metadata>
    <category
        name="Form Widgets">
        <view
            class="android.widget.TextView"
            name="TextView"
            init=""
            relatedTo="EditText,AutoCompleteTextView,MultiAutoCompleteTextView">
            <view
                name="Large Text"
                init="android:textAppearance=?android:attr/textAppearanceLarge" />
            <view
                name="Medium Text"
                init="android:textAppearance=?android:attr/textAppearanceMedium" />
            <view
                name="Small Text"
                init="android:textAppearance=?android:attr/textAppearanceSmall" />
        </view>
        <view
            class="android.widget.Button"
            relatedTo="ImageButton" />
        <view
            class="android.widget.ToggleButton"
            relatedTo="CheckBox" />
        <view
            class="android.widget.CheckBox"
            relatedTo="RadioButton,ToggleButton,CheckedTextView" />
        <view
            class="android.widget.RadioButton"
            relatedTo="CheckBox,ToggleButton" />
        <view
            class="android.widget.CheckedTextView"
            relatedTo="TextView,CheckBox" />
        <view
            class="android.widget.Spinner"
            relatedTo="EditText"
            fill="width_in_vertical" />
        <view
            class="android.widget.ProgressBar"
            relatedTo="SeekBar"
            name="ProgressBar (Large)"
            init="style=?android:attr/progressBarStyleLarge">
            <view
                name="ProgressBar (Normal)"
                init="" />
            <view
                name="ProgressBar (Small)"
                init="style=?android:attr/progressBarStyleSmall" />
            <view
                name="ProgressBar (Horizontal)"
                init="style=?android:attr/progressBarStyleHorizontal" />
        </view>
        <view
            class="android.widget.SeekBar"
            relatedTo="ProgressBar"
            fill="width_in_vertical" />
        <view
            class="android.widget.QuickContactBadge" />
        <view
            class="android.widget.RadioGroup" />
        <view
            class="android.widget.RatingBar" />
    </category>
    <category
        name="Text Fields">
        <view
            class="android.widget.EditText"
            name="Plain Text"
            init=""
            relatedTo="Spinner,TextView,AutoCompleteTextView,MultiAutoCompleteTextView"
            fill="width_in_vertical">
            <view
                name="Person Name"
                init="android:inputType=textPersonName" />
            <view
                name="Password"
                init="android:inputType=textPassword" />
            <view
                name="Password (Numeric)"
                init="android:inputType=numberPassword" />
            <view
                name="E-mail"
                init="android:inputType=textEmailAddress" />
            <view
                name="Phone"
                init="android:inputType=phone" />
            <view
                name="Postal Address"
                init="android:inputType=textPostalAddress" />
            <view
                name="Multiline Text"
                init="android:inputType=textMultiLine" />
            <view
                name="Time"
                init="android:inputType=time" />
            <view
                name="Date"
                init="android:inputType=date" />
            <view
                name="Number"
                init="android:inputType=number" />
            <view
                name="Number (Signed)"
                init="android:inputType=numberSigned" />
            <view
                name="Number (Decimal)"
                init="android:inputType=numberDecimal" />
        </view>
        <view
            class="android.widget.AutoCompleteTextView"
            fill="width_in_vertical" />
        <view
            class="android.widget.MultiAutoCompleteTextView"
            fill="width_in_vertical" />
    </category>
    <category
        name="Layouts">
        <view
            class="android.widget.LinearLayout"
            name="LinearLayout (Vertical)"
            init="android:orientation=vertical"
            icon="VerticalLinearLayout"
            fill="opposite"
            render="skip">
            <view
                name="LinearLayout (Horizontal)" />
        </view>
        <view
            class="android.widget.RelativeLayout"
            fill="opposite"
            render="skip" />
        <view
            class="android.widget.FrameLayout"
            fill="opposite"
            render="skip" />
        <view
            class="include"
            name="Include Other Layout"
            render="skip" />
        <view
            class="android.widget.TableLayout"
            fill="opposite"
            render="skip" />
        <view
            class="android.widget.TableRow"
            fill="opposite"
            render="skip" />
    </category>
    <category
        name="Composite">
        <view
            class="android.widget.ListView"
            relatedTo="ExpandableListView"
            fill="width_in_vertical"
            render="skip" />
        <view
            class="android.widget.ExpandableListView"
            relatedTo="ListView"
            fill="width_in_vertical"
            render="skip" />
        <view
            class="android.widget.TwoLineListItem"
            render="skip" />
        <view
            class="android.widget.GridView"
            fill="opposite"
            render="skip" />
        <view
            class="android.widget.ScrollView"
            relatedTo="HorizontalScrollView"
            fill="opposite"
            render="skip" />
        <view
            class="android.widget.HorizontalScrollView"
            relatedTo="ScrollView"
            render="skip" />
        <view
            class="android.widget.SearchView"
            render="skip" />
        <view
            class="android.widget.SlidingDrawer" />
        <view
            class="android.widget.TabHost"
            fill="width_in_vertical"
            render="alone" />
        <view
            class="android.widget.TabWidget"
            render="alone" />
        <view
            class="android.webkit.WebView"
            fill="opposite"
            render="skip" />
    </category>
    <category
        name="Images &amp; Media">
        <view
            class="android.widget.ImageView"
            relatedTo="ImageButton,VideoView" />
        <view
            class="android.widget.ImageButton"
            relatedTo="Button,ImageView" />
        <view
            class="android.widget.Gallery"
            fill="width_in_vertical"
            render="skip" />
        <view
            class="android.widget.MediaController"
            render="skip" />
        <view
            class="android.widget.VideoView"
            relatedTo="ImageView"
            fill="opposite"
            render="skip" />
    </category>
    <category
        name="Time &amp; Date">
        <view
            class="android.widget.TimePicker"
            relatedTo="DatePicker,CalendarView"
            render="alone" />
        <view
            class="android.widget.DatePicker"
            relatedTo="TimePicker"
            render="alone" />
        <view
            class="android.widget.CalendarView"
            relatedTo="TimePicker,DatePicker" />
        <view
            class="android.widget.Chronometer" />
        <view
            class="android.widget.AnalogClock"
            relatedTo="DigitalClock" />
        <view
            class="android.widget.DigitalClock"
            relatedTo="AnalogClock" />
    </category>
    <category
        name="Transitions">
        <view
            class="android.widget.ImageSwitcher"
            relatedTo="ViewFlipper,ViewSwitcher,TextSwitcher"
            render="skip" />
        <view
            class="android.widget.AdapterViewFlipper"
            fill="opposite"
            render="skip" />
        <view
            class="android.widget.StackView"
            fill="opposite"
            render="skip" />
        <view
            class="android.widget.TextSwitcher"
            relatedTo="ViewFlipper,ImageSwitcher,ViewSwitcher"
            fill="opposite"
            render="skip" />
        <view
            class="android.widget.ViewAnimator"
            fill="opposite"
            render="skip" />
        <view
            class="android.widget.ViewFlipper"
            relatedTo="ViewSwitcher,ImageSwitcher,TextSwitcher"
            fill="opposite"
            render="skip" />
        <view
            class="android.widget.ViewSwitcher"
            relatedTo="ViewFlipper,ImageSwitcher,TextSwitcher"
            fill="opposite"
            render="skip" />
    </category>
    <category
        name="Advanced">
        <view
            class="android.view.View"
            render="skip" />
        <view
            class="android.view.ViewStub"
            render="skip" />
        <view
            class="android.gesture.GestureOverlayView"
            render="skip" />
        <view
            class="android.view.SurfaceView"
            render="skip" />
        <view
            class="android.widget.NumberPicker"
            relatedTo="TimePicker,DatePicker"
            render="alone" />
        <view
            class="android.widget.ZoomButton"
            relatedTo="Button" />
        <view
            class="android.widget.ZoomControls" />
        <view
            class="merge"
            skip="true"
            render="skip" />
        <view
            class="android.widget.DialerFilter"
            fill="width_in_vertical"
            render="skip" />
        <view
            class="android.widget.AbsoluteLayout"
            fill="opposite"
            render="skip" />
    </category>
    <category
        name="Other">
        <!--  This is the catch-all category which contains unknown views if we encounter any -->
    </category>
    <!--  TODO: Add-ons? -->
</metadata>
